### ISSUE TITLE
Compiler mismatch and full paths

### ISSUE THREAD

**Issue by bonachea** [BerkeleyLab/caffeine#28]
Just got an installer mismatch:
```
$ env CC=gcc CXX=g++ FC=gfortran ./install.sh 
PREFIX=<redacted>/bonachea/.local
PKG_CONFIG_PATH=<redacted>/bonachea/.local/lib/pkgconfig
GASNET_CC=/usr/local/pkg/gcc/11.2.0/bin/gcc and FPM_CC=gcc don't match
```

The workaround:
```
$ env CC=`which gcc` CXX=`which g++` FC=`which gfortran` ./install.sh
```
but should not be necessary...

GASNET_CC is usually absified automatically by configure.
install.sh should absify both commands (e.g. via `type -p $FPM_CC`) before comparing them.
Arguably you should also absify the `$FPM_FC` value you save, to ensure proper operation after a `$PATH` change.

**Comment by wyphan** [comment]
This also happens if GASNet-EX and fpm are installed using Spack, because packages installed with Spack are built using the Spack compiler wrappers instead of directly using the full path of the compiler, but somehow fpm evades using the Spack compiler wrappers, even when fpm is built and installed using Spack!

```console
GASNET_CC=/opt/spack/lib/spack/env/gcc/gcc and FPM_CC=/opt/spack/opt/spack/linux-ubuntu22.04-zen2/gcc-11.2.0/gcc-11.3.0-pp7jwyvfwxqrt4sz3nw2mzbus6fyowlh/bin/gcc don't match
```

Steps to reproduce:
```bash
spack install gcc@11.3.0
spack load gcc@11.3.0
spack compiler find
spack install fpm %gcc@11.3.0
spack install gasnet %gcc@11.3.0
spack load fpm
spack load gasnet
cd caffeine
./install.sh
```

**Comment by wyphan** [comment]
PR #31 drafted to address this issue.
